/** API Keys module health indicator for NestJS.
 *  Generated by RapidKit.
 */

import {
  Controller,
  Get,
  HttpCode,
  HttpStatus,
  Logger,
  ServiceUnavailableException,
} from "@nestjs/common";

import { ApiKeysService } from "../modules/free/auth/api_keys/api-keys.service";

interface HealthPayload {
  status: string;
  totals: Record<string, number>;
  issues: string[];
  metadata: Record<string, unknown>;
}

@Controller("api/health/module")
export class ApiKeysHealthController {
  private readonly logger = new Logger(ApiKeysHealthController.name);

  constructor(private readonly service: ApiKeysService) {}

  @Get("api-keys")
  @HttpCode(HttpStatus.OK)
  getModuleHealth(): HealthPayload {
    try {
      const payload = this.service.getHealth();
      this.logger.debug(
        `API Keys health payload=${JSON.stringify(payload)}`,
      );
      return payload as HealthPayload;
    } catch (error) {
      const detail =
        error instanceof Error && error.message ? error.message : "API Keys health check failed";
      this.logger.error(`API Keys health check failed: ${detail}`);
      throw new ServiceUnavailableException({
        status: "error",
        module: "free/auth/api_keys",
        detail,
      });
    }
  }
}
